# https://dart.dev/guides/language/analysis-options
include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    comment_references: ignore # too many false positives

linter:
  rules:
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - literal_only_boolean_expressions
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_runtimeType_toString
    - package_api_docs
    - unnecessary_await_in_return
