// Copyright (c) 2026, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// Parses a single hex character byte (0-9, a-f, A-F) to its integer value.
/// Returns a negative value if the byte is not a valid hex character.
@pragma('vm:prefer-inline')
int parseHex(int byte) {
  assert(byte >= 0 && byte <= 255);
  final entry = _charFlags.codeUnitAt(byte);
  return entry.toSigned(8);
}

/// Whether the byte is a valid HTTP token character (tchar).
@pragma('vm:prefer-inline')
bool isTchar(int byte) {
  assert(byte >= 0 && byte <= 255);
  return (_charFlags.codeUnitAt(byte) & _nonTChar) == 0;
}

/// Whether the byte is an invalid character in a header value.
@pragma('vm:prefer-inline')
bool isInvalidHeaderValueChar(int byte) {
  assert(byte >= 0 && byte <= 255);
  return (_charFlags.codeUnitAt(byte) & _nonHeaderChar) != 0;
}

/// Whether the byte is an invalid character in a URL.
@pragma('vm:prefer-inline')
bool isInvalidUrlChar(int byte) {
  assert(byte >= 0 && byte <= 255);
  return (_charFlags.codeUnitAt(byte) & _nonUrlChar) != 0;
}

// --------------------------------------------------------------------
// The declarations below can be generated by the script
// `tool/create_char_info_table.dart`.
// Modify that script if changing table layout.

// Bit masks for the bits in `_charFlags`.
// Chosen so that they are not set for a hex digit.

/// Bit set when the character is invalid in a URL.
const int _nonUrlChar = 0x10;

/// Bit set when the character is not a valid HTTP token character (tChar).
const int _nonTChar = 0x20;

/// Bit set when the character is not a valid in an HTTP header value.
const int _nonHeaderChar = 0x40;

/// A lookup table for character classification and parsing.
///
/// This table contains 256 entries, one for each byte value.
/// The bits of each entry encode multiple properties of the character:
///
/// *   **Bits 0-3:** The numeric value of the hex digit (0-15), if applicable.
/// *   **Bit 4 (0x10):** Flag set if the character is invalid in a URL.
/// *   **Bit 5 (0x20):** Flag set if the character is not a valid HTTP token
///     character (tChar).
/// *   **Bit 6 (0x40):** Flag set if the character is not a valid in an HTTP
///     header value.
/// *   **Bit 7 (0x80):** Flag set if the character is not a hex digit a URL.
///
/// This layout allows extremely fast checks in performance-critical parsing
/// loops by avoiding multiple conditional branches.
const String _charFlags =
    '\xF0\xE0\xE0\xE0\xE0\xE0\xE0\xE0\xE0\xA0\xF0\xE0\xE0\xB0\xE0\xE0'
    '\xE0\xE0\xE0\xE0\xE0\xE0\xE0\xE0\xE0\xE0\xE0\xE0\xE0\xE0\xE0\xE0'
    '\xA0\x80\xA0\x80\x80\x80\x80\x80\xA0\xA0\x80\x80\xA0\x80\x80\xA0'
    '\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\xA0\xA0\xA0\xA0\xA0\xA0' // ignore: missing_whitespace_between_adjacent_strings
    '\xA0\x0A\x0B\x0C\x0D\x0E\x0F\x80\x80\x80\x80\x80\x80\x80\x80\x80' // ignore: missing_whitespace_between_adjacent_strings
    '\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\xA0\xA0\xA0\x80\x80'
    '\x80\x0A\x0B\x0C\x0D\x0E\x0F\x80\x80\x80\x80\x80\x80\x80\x80\x80' // ignore: missing_whitespace_between_adjacent_strings
    '\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\xA0\x80\xA0\x80\xE0'
    '\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0'
    '\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0'
    '\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0'
    '\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0'
    '\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0'
    '\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0'
    '\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0'
    '\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0\xB0';
