sdk:
- pubspec
- dev

stages:
- analyze_and_format:
  - analyze: --fatal-infos .
  - format:
    sdk:
    - dev
- unit_test:
  - test: --test-randomize-ordering-seed=random
    os:
    - linux
    - windows
